// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iPieShop.Web.Models;

namespace iPieShop.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191204204757_Seeded")]
    partial class Seeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("iPieShop.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Category 5"
                        });
                });

            modelBuilder.Entity("iPieShop.Web.Models.Pie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "SOME DESCRIPTION HERE",
                            ImageUrl = "SOME IMAGE HERE",
                            Name = "SOME NAME HERE",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "SOME DESCRIPTION HERE",
                            ImageUrl = "SOME IMAGE HERE",
                            Name = "SOME NAME HERE",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "SOME DESCRIPTION HERE",
                            ImageUrl = "SOME IMAGE HERE",
                            Name = "SOME NAME HERE",
                            Price = 3000.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "SOME DESCRIPTION HERE",
                            ImageUrl = "SOME IMAGE HERE",
                            Name = "SOME NAME HERE",
                            Price = 4000.0
                        });
                });

            modelBuilder.Entity("iPieShop.Web.Models.Pie", b =>
                {
                    b.HasOne("iPieShop.Web.Models.Category", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
